title: KVQA Dataset
description: 우리말을 사용하는 시각장애인들을 위한 시각 질의 응답 데이터셋
show_downloads: true
google_analytics: 150642064
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/SKTBrain/BAN-KVQA
  zip_url: https://drive.google.com/drive/folders/1hqnCxlWq5JAxnj_wsXjteH0UFhS7RMHW?usp=sharing
